### ISSUE TITLE
Stop refreshing after php error

### ISSUE THREAD

**Issue by PixelT** [BrowserSync/browser-sync#929] opened 2015-12-12 09:36 UTC
When I have error in PHP, after the next save files, the refresh doesn't work
I must refresh browser manually, then the browser-sync will be work again

**Comment by shakyShane** [comment] 2015-12-19 20:59
The problem is that although PHP errors are sent with the following header...

`Content-Type: text/html; charset=UTF-8`

... the actual content (containing the error) does not have a `<body>` tag so the snippet injection fails.

You can force the snippet to be added to all documents with the following option, this will simply append it to the end of every page (even outside of the closing body/html). It sounds crazy, but I've tested this extensively and it seems to work across all major browser and is exactly how snippet injection will work in V3 that's coming soon.

```js
var bs = require('browser-sync');

bs.init({
    proxy: 'http://yourphpsite.dev',
    snippetOptions: {
        rule: {
            match: /$/
        }
    }
});
```

**Closed by shakyShane** 2015-12-19 20:59 UTC
