### ISSUE TITLE
PHP session issue with browser-sync & laravel artisan serve

### ISSUE THREAD

**Issue by NgYueHong** [BrowserSync/browser-sync#637] opened 2015-05-22 08:23 UTC
I am running my laravel 5 app with php artisan serve and using browser-sync to proxy it to bring live-reload to my browser.

But the problem is, php artisan create new session on every request. This causes problem that I cannot login to my webpage, which uses php session to track user login.

This problem only occur when I access the webpage through browser-sync proxy. If access directly from the artisan serve server, everything is working fine.

Hope there is a fix for this soon.

**Comment by shinnn** [comment] 2015-05-22 11:15
Maybe this is a duplicate of #635?

**Comment by shinnn** [comment] 2015-05-22 15:09
Discussion goes to #635.

**Closed by shinnn** 2015-05-22 15:09 UTC
