### ISSUE TITLE
Proxy in Firefox Prevents Navigation

### ISSUE THREAD

**Issue by thisisjamessmith** [BrowserSync/browser-sync#1570] opened 2018-06-06 13:46 UTC
I found this problem has returned in version 2.24.4 of BrowserSync. I rolled the version back to 2.23.6 (because that was a previous project where I knew it was working ok), and the problem went away.

Full details in the original issue:

https://github.com/BrowserSync/browser-sync/issues/386

**Comment by alexandernanberg** [comment] 2018-06-07 06:31
I'm having the same problem, only occurs when the page I'm trying to navigate is not loaded instantly

**Comment by jdmrgtnj** [comment] 2018-06-07 20:15
I can confirm this, and tried adding 'reloadOnStart: false;' from previous bug fix with no luck.

**Comment by lkraav** [comment] 2018-07-07 19:35
Indeed, there seems to be a regression. I also have `"reloadOnRestart": false` in place from the past with code comment pointing https://github.com/BrowserSync/browser-sync/issues/435#issuecomment-96272944

Yet, 2.24.5 is still messing up navigation in Firefox. I will downgrade to 2.23.

**Comment by moaxey** [comment] 2018-07-26 04:49
npm install browser-sync@2.23.7

**Comment by jdmrgtnj** [comment] 2018-07-26 13:47
awesome, working like a champ

**Comment by AndreaBarghigiani** [comment] 2018-08-05 15:45
I had the same issue usign 2.24.6 and the strange thing is that with the simple Firefox I could navigate the site normally but when I use Firefox Developer Edition I got the same error.

Now I've rolled back as suggested by @moaxey but I would like to undestand better why this is happening.

**Comment by aleksip** [comment] 2018-08-09 20:07
I had the same problem with both Firefox and Firefox Developer Edition, and can confirm that rolling back to 2.23.7 fixed it.

**Comment by muuvmuuv** [comment] 2018-09-12 12:02
Is someone looking into this to fix it? Can't be so difficult when it was working until 2.23.7

**Comment by abmaonline** [comment] 2018-10-06 13:02
Could the fix for https://github.com/BrowserSync/browser-sync/issues/1591 have any effect on this issue (since it was also related to unexpected reloads)?

Have been working with https://github.com/BrowserSync/browser-sync/releases/tag/v2.26.0 for the last hour and haven't seen any unexpected reloads or navigation issues in Firefox or Firefox Developer Edition...

**Comment by shakyShane** [comment] 2018-10-06 18:43
@abmaonline yeah good spot - this will also be fixed in 2.26.0 :)

**Closed by shakyShane** 2018-10-06 18:43 UTC
