### ISSUE TITLE
Runing multiple instances of browser-sync on same port cause undocumented behavior

### ISSUE THREAD

**Issue by 07pepa** [BrowserSync/browser-sync#1585] opened 2018-07-19 17:31 UTC
### Issue details/steps to reproduce
multiple instances of browser-sync disobey selected port(CLI)... except 1st one.... and there should be way(at least hacky one like make request to port) how to check if some instance of  browser-sync is runing and just open broswer and terminate.... or at least  throw exception or something not just make new port that chage adress of server and break stuff.... this is ***UNDOCUMENTED BEHAVIOR**

### versions
- Browsersync [2.24.5]
- Node        [ v8.11.3  ]
- Npm         [   5.6.0 ]

### Affected platforms
- [x] windows is only one confirmed but  I guess everything is affected

### Browsersync use-case
- [YES] CLI
### CLI COMAND
{browser-sync start --server -f -w --no-ui --port 3000}

**Comment by shakyShane** [comment] 2018-08-26 15:14
duplicate of https://github.com/BrowserSync/browser-sync/issues/312

**Closed by shakyShane** 2018-08-26 15:14 UTC
