### ISSUE TITLE
PHP Cookie proxy issue

### ISSUE THREAD

**Issue by patrickjaja** [BrowserSync/browser-sync#703] opened 2015-07-01 11:58 UTC
Background: Using PHP (5.4.7) in the backend, called by JS in frontend. Gulp is running with browser-sync ("browser-sync": "^2.7.13") in proxy mode.

gulp part:
```js
gulp.task('browser-sync',['php'], function() {
  browserSync({
      proxy: '127.0.0.1:8010', //<-- PHP
      startPath: 'app',
      port: 80, //<-- Browser
      open: true,
      notify: false
  });
});
```

PHP part: 
```js
<?php
//set a cookie
setcookie("test-name-1","test-value-1");
setcookie("test-name-2","test-value-2", time()+3600, "/");

//WTF here is no $_COOKIE?
print_r($_COOKIE);die();
```

Reproduce:
1. Run browserSync with PHP in proxy mode
2. Create a file with this PHP snipped and have a look to the output (its empty)

Browser Output in BrowserSync PHP Proxy mode:
```js
Array
(
)
```

Browser Output in Apache + PHP (xampp)
```js
Array
(
    [test-name-1] => test-value-1
    [test-name-2] => test-value-2
)
```

Why i cannot access to the PHP cookies using BrowserSync?

Thanks for your time.

**Comment by chimurai** [comment] 2015-07-11 21:12
Looks like a duplicate of https://github.com/BrowserSync/browser-sync/issues/471#issuecomment-102418834

**Comment by shinnn** [comment] 2015-07-12 01:35
Indeed. Thanks, @chimurai.

**Closed by shinnn** 2015-07-12 01:35 UTC
