### ISSUE TITLE
Question: Is it possible to embed browser sync on a remote web server?

### ISSUE THREAD

**Issue by StfBauer** [BrowserSync/browser-sync#968] opened 2016-01-19 15:58 UTC
I was just curious if there is a way to embed browser sync on a remote web site and refresh that page when something changes in my local file system.
The scenario is like this. I have a wordpress instance installed on a remote server and like to develop some style sheets using sass. For style sheet development I just have my local node instance and gulp files doing all the css compilation for me.
Through browser sync I got a web site from where I am able to reference the style sheets and javascript files just like you make use of those resources from a CDN.
Sadly I haven't found any documentation about such scenario. The other possibility might is I'm blind.

Thank you in advance.

**Comment by marvinhagemeister** [comment] 2016-01-19 21:11
Have a look at the proxy option. Just fire up browsersync locally and inject the compiled css.

**Comment by StfBauer** [comment] 2016-01-20 23:17
I think I got it working. The remote server requires authentication and when I launch the browser sync I will be asked for authentication but somehow I cannot authenticate.

Any suggestion on this issue?

**Comment by shakyShane** [comment] 2016-01-26 07:44
@StfBauer closing this issue as it now seems a dupe of https://github.com/BrowserSync/browser-sync/issues/969 :)

**Closed by shakyShane** 2016-01-26 07:44 UTC
