### ISSUE TITLE
HTTP/2 Support

### ISSUE THREAD

**Issue by rolandjitsu** [BrowserSync/browser-sync#990] opened 2016-02-08 07:15 UTC
It would be nice to have support for HTTP/2 when using the static server you provide. This would make dev a lot faster when using ES6 imports.

**Comment by shakyShane** [comment] 2016-02-08 07:55
dupe of https://github.com/BrowserSync/browser-sync/issues/766

**Closed by shakyShane** 2016-02-08 07:55 UTC
