### ISSUE TITLE
Getting error on install ... \\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

### ISSUE THREAD

**Issue by born2net** [BrowserSync/browser-sync#993] opened 2016-02-11 18:18 UTC
Getting error on install node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

regards

Sean

**Comment by dreamyguy** [comment] 2016-02-14 14:04
The problem is with `bufferutil`. Have a look at https://github.com/websockets/bufferutil/issues. I came across https://github.com/howdyai/botkit/issues/2, but haven't tried their fix. Unsure if I got this after a system upgrade on my OSX, which involved XCode...

**Comment by StfBauer** [comment] 2016-02-15 09:24
On windows you have to install python 2.7 too out install browser-sync with --no-optional. Then you will avoid this error. bufferutil try to compile the python scripts with node-gyp. Those components are just for quicker responses but works even without them too.

**Comment by dreamyguy** [comment] 2016-02-15 09:56
@StfBauer yes, I did notice that `browser-sync` works fine even without it, so it's not a show-stopper. Cheers for the clarification! :+1:

**Comment by StfBauer** [comment] 2016-02-15 11:26
@dreamyguy No problem. What I heard is that node.js working on a native implementation on web sockets. This brings the benefits that you don't have to rely on this part anymore.

**Comment by born2net** [comment] 2016-02-15 15:32
ok, not a show stopper, just nicer if no errors... tx

**Comment by dreamyguy** [comment] 2016-02-15 17:12
This problem disappeared after I activated XCode by running:

`sudo xcodebuild -license`

XCode Version 7.2.1 (7C1002)
node v4.3.0
npm 2.14.12

**Comment by born2net** [comment] 2016-02-15 17:18
I am in Windows...

**Comment by shakyShane** [comment] 2016-02-18 21:18
Closing as this does not stop the installation process

**Closed by shakyShane** 2016-02-18 21:18 UTC
