### ISSUE TITLE
Latest release v2.18.5  is breaking change for node.js 0.12.9

### ISSUE THREAD

**Issue by jnmandal** [BrowserSync/browser-sync#1270] opened 2016-12-12 18:48 UTC
### Issue details

Hi all, not sure if a bug or a feature but your latest release seems to drop support for node.js 0.12.9. It was working fine until yesterday but now we get:

```
nothing/to/see/here/node_modules/browser-sync/node_modules/portscanner/node_modules/is-number-like/lib/index.js:2
const isNumber = require('lodash.isfinite')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/nothing/to/see/here/node_modules/browser-sync/node_modules/portscanner/lib/portscanner.js:4:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Perhaps you want to check your semver, or perhaps this was intentional (as LTS support has ended). We've had to downgrade until we can upgrade our nodejs.

### Steps to reproduce/test case

_Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies)_.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.18.5 ]
- Node        [ 0.12.9 ]
- Npm         [ 2.14.9 ]

### Affected platforms

- [x] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by tedwardmah** [comment] 2016-12-12 22:52
@shakyShane thanks for looking into this.  I noticed the same issue starting today when we deploy.

**Comment by danielquijada** [comment] 2016-12-13 09:16
What caused this on: https://github.com/vigour-io/is-number-like/issues/3 (in case you haven't had time to look into this).

**Comment by rachelf-teamddm** [comment] 2016-12-13 16:31
I am also getting this error, it looks like portscanner was updated to 2.1.1 which now includes in-number-like and thats breaking things.

**Comment by NareshBanala** [comment] 2016-12-13 17:50
There is a pull request on is-number-like which fixes root cause of the . 
https://github.com/vigour-io/is-number-like/pull/7

**Comment by marioagarcia** [comment] 2016-12-13 18:24
One of the authors of is-number-like said that he will merge the pull request in a couple of hours

**Comment by shakyShane** [comment] 2016-12-13 19:24
@marioagarcia thanks, let's wait till that happens.

I'm eager to fix this, but out of interest, what is keeping you all on < node 4?

There will come a time very soon when more and more libraries/tools will stop supporting 0.10 & 0.12, so I would suggest updating as soon as possible :)

**Comment by jnmandal** [comment] 2016-12-13 19:32
@shakyShane Mainly constrained by operations backlog though there are definitely some dependency issues w/ 4.x.x in one or two projects that are currently on 0.12.x. Upgrading is definitely on the radar since LTS/maintenance ends this month.

**Comment by jimdebeer** [comment] 2016-12-13 20:46
I merged it sorry for the pkg -- been so long since io.js we sort of forgot about older versions :/

**Comment by jnmandal** [comment] 2016-12-13 21:04
thanks @jimdebeer @shakyShane and all browser-sync folks; we the users really appreciate your work!

**Comment by shakyShane** [comment] 2016-12-13 21:06
More than welcome. We do open source to help, that's all that matters.

**Comment by shakyShane** [comment] 2016-12-13 21:07
now the fix is out, there's nothing I can do from a Browsersync point of view, better to just re-install and you'll get the upstream fixes (as port-scanner) is using ^ dep guard

**Comment by shakyShane** [comment] 2016-12-13 21:09
Thanks for the speedy response @jimdebeer

**Closed** 2016-12-13 21:08 UTC
Labels: bug, CRITICAL
