### ISSUE TITLE
Restrict input from devices

### ISSUE THREAD

**Issue by ottosmittenaar** [BrowserSync/browser-sync#704] opened 2015-07-01 15:27 UTC
Hi,

I really love this project and would like to use it to demonstrate our web projects. Therefor I would like to restrict the input control of specific devices. I could not find anything about it in the documentation. Also I looked at all the issues and could not find a similar issue. Could somebody help me with this?

Best regards,
Otto Smittenaar

**Comment by shakyShane** [comment] 2015-07-03 09:54
dupe of #550 & #587 - please continue conversations there.

**Closed by shakyShane** 2015-07-03 09:54 UTC
