### ISSUE TITLE
console socket.io spam

### ISSUE THREAD

**Issue by benoneal** [BrowserSync/browser-sync#490] opened 2015-02-27 07:45 UTC
When BrowserSync is running, the console is just constantly spammed with the following every few milliseconds: 
```
engine.io-client:socket socket receive: type "pong", data "undefined" +1ms
engine.io-client:socket writing ping packet - expecting pong within 60000ms +6ms
```

This makes standard debugging with console.log() impossible, and floods out any other logging. Is there an option or something I can do to disable this message?

**Comment by shinnn** [comment] 2015-02-27 16:25
I can't reproduce that.

* Which OS?
* Which browser?
* Node version?
* browser-sync version?
* CLI or API?

**Comment by benoneal** [comment] 2015-03-02 00:29
OSX Yosemite
Chrome & Firefox (screenshots below)
0.12.0
2.2.1
API

Here's some screenshots of the console logging: 
![screen shot 2015-03-02 at 10 27 07 am](https://cloud.githubusercontent.com/assets/4063875/6433920/ecd5350e-c0c6-11e4-87da-234ec7135a3b.png)
![screen shot 2015-03-02 at 10 27 50 am](https://cloud.githubusercontent.com/assets/4063875/6433921/ecd81bde-c0c6-11e4-8d4f-9da504518653.png)

**Comment by shinnn** [comment] 2015-03-02 00:37
> API

Could you show us the script?

**Comment by benoneal** [comment] 2015-03-02 00:38
Sure: 
```
gulp.task('sync', ['serve'], function(cb) {
  browserSync.init({
    files: ['build/**/*.*'],
    ui: { port: 9090 },
    proxy: 'localhost:9000',
    port: 9001,
    notify: false,
    https: false
  }, cb);
});
```

**Comment by shinnn** [comment] 2015-03-02 00:48
I still cannot reproduce the logs like that...

How do you host the `localhost:9000` site? Other program?

**Comment by benoneal** [comment] 2015-03-02 00:51
Express server, instantiated through Nodemon. It's an isomorphic React app. I use Express for the server, React + Fluxible for the app, Webpack to bundle js, and Gulp to manage all other assets.

**Comment by koba04** [comment] 2015-03-02 10:19
I got the same issue on Chrome 40.0.2214.115 (OSX 10.10.1, node v0.10.33) .
Chrome Canary 43.0.2316.0, Safari 8.0.2, and Firefox 36.0 didn't reproduce.

minimum code is:
```js
'use strict';
var browserSync = require('browser-sync');

browserSync({
  server: 'public',
  files: 'public/index.html'
});
```

**Comment by koba04** [comment] 2015-03-02 10:21
browser-sync version is 2.2.1.

**Comment by shinnn** [comment] 2015-03-02 11:09
* Mac OS X Yosemite 10.10.2
* Chrome 43.0.2318.2 canary (64-bit)
* io.js 1.4.2
* browser-sync v2.2.1
* HTML
  ```html
  <!doctype html>
  <html class="no-js" lang="">
      <head>
          <meta charset="utf-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <title></title>
          <meta name="description" content="">
          <meta name="viewport" content="width=device-width, initial-scale=1">

          <link rel="apple-touch-icon" href="apple-touch-icon.png">
          <!-- Place favicon.ico in the root directory -->
      </head>
      <body>
          <!--[if lt IE 8]>
              <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
          <![endif]-->

          <!-- Add your site or application content here -->
          <p>Hello world! This is HTML5 Boilerplate.</p>

          <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
          <script>
              (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
              function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
              e=o.createElement(i);r=o.getElementsByTagName(i)[0];
              e.src='//www.google-analytics.com/analytics.js';
              r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
              ga('create','UA-XXXXX-X','auto');ga('send','pageview');
          </script>
      </body>
  </html>
  ```
* Server
  ```js
  'use strict';
  var browserSync = require('browser-sync');

  browserSync({
    server: 'public',
    files: 'public/index.html'
  });
  ```
* log
  
![image](https://cloud.githubusercontent.com/assets/1131567/6439612/a6f2a232-c117-11e4-82e6-bdc9275120f3.png)

:(

I'll try it again with different Node versions...

**Comment by shinnn** [comment] 2015-03-02 11:11
@koba04 Does your Chrome produce exactly the same logs as @benoneal's?

**Comment by shinnn** [comment] 2015-03-02 12:57
Ah, OK. I found a temporary solution.

1. Open the browser console on your site (which spamming a lot of logs)
2. Type `localStorage.debug = ''` and :leftwards_arrow_with_hook: 
3. Reload the browser

Maybe this will do the trick.

**Comment by koba04** [comment] 2015-03-03 01:02
@shinnn 
Yes, logs are same as @benoneal's.
I tried the way that you taught me, it occurs no longer!
Thank you!

**Comment by benoneal** [comment] 2015-03-03 22:47
@shinnn: Thanks for looking into this for us. Is a more permanent fix in the works? We're using this across a team of 30 developers and would rather not have to require them all to re-assign their browser's localStorage.debug.

**Comment by shinnn** [comment] 2015-03-04 04:19
@benoneal Yes, I also want to fix this problem fundamentally.

@shakyShane We should exclude [debug](https://github.com/visionmedia/debug) module from the client-side script anyway.

**Comment by benoneal** [comment] 2015-03-08 23:33
In case it helps, that ```localStorage.debug = ''``` trick didn't work at all for me in Chrome. Didn't try any other browsers though.

**Comment by shakyShane** [comment] 2015-04-12 16:32
There's nothing in the BrowserSync source code would cause this logging, so I think it's a fair decision to close this. That being said, I'd be happy to work on a solution should a sample project be provided that can reproduce this problem.

**Closed by shakyShane** 2015-04-12 16:32 UTC

**Comment by eriknyk** [comment] 2015-09-17 18:04
but @shakyShane 

this line says that is browser-sync code line
browser-sync-client.2.5.1.js:2 engine.io-client:socket writing ping packet - expecting pong within 60000ms +5s

and its shows that  call is being made from: browser-sync-client.2.5.1.js
```
function log(){return"object"==typeof console&&"function"==typeof console.log&&Function.prototype.apply.call(console.log,console,arguments)}
```

**Comment by friksa** [comment] 2016-01-19 09:38
Having the same issue here on OS X 10.11

**Comment by amin101** [comment] 2016-03-09 13:18
having the same issue here on Win 7 - mozila firefox 45. it is really annoying

**Comment by ramiyahya** [comment] 2016-10-20 10:44
Having the same issue on 
Sierra OSX 10.12
Latest Chrome
Node 6
