### ISSUE TITLE
Reloading using a stream doesn't work correctly

### ISSUE THREAD

**Issue by thasmo** [BrowserSync/browser-sync#561] opened 2015-04-07 21:55 UTC
My watch task looks like this:
```js
gulp.task('watch', function() {
	browserSync({server: {baseDir: 'public'}}, function() {
		gulp.watch('public/**').on('change', function(file) {
			gulp.src(file.path)
				.pipe($.filter(['!*.map']))
				.pipe(browserSync.reload({stream: true}));
		});
	});
});
```
I'm starting the BrowserSync server and in the callback I start watching any file changes in the public directory. When a file gets changed, in my case `main.css`, I source the file with gulp (filter out source-map files) and pipe the file to the reload function of BrowserSync, which silently fails.

The linked stylesheet is referenced using `<link rel="stylesheet" href="/static/style/main.css">` inside the index.html file.

When not filtering out the source-map files, BrowserSync *correctly* reloads the URL, because it doesn't know how to inject it, which is fine. Unfortunately it does not apply any changes which were made in the `main.css` file, when filtering out the source-map file.

Any idea why this may be?

**Comment by shakyShane** [comment] 2015-04-12 19:47
Why are you doing this at all?

```js
gulp.src(file.path)
    .pipe($.filter(['!*.map']))
    .pipe(browserSync.reload({stream: true}));
```

Why not just do a simpler check on the file path and then call reload manually? I think you are confusing things by creating a stream here as it's not needed.

```js
gulp.task('watch', function() {
    browserSync({server: {baseDir: 'public'}}, function() {
        gulp.watch('public/**').on('change', function(file) {
            if (file.path.match(/\.css$/)) {
                browserSync.reload(file);
            }
        });
    });
});
```

Closing this as it's not an *issue* with BrowserSync, but happy to continue the thread to help you solve your workflow

**Closed by shakyShane** 2015-04-12 19:47 UTC

**Comment by thasmo** [comment] 2015-04-13 19:31
@shakyShane, thanks for your feedback. Your example works and that's what I tried before, but the problem is that browser-sync reloads the entire page. Shouldn't it just inject CSS files directly without reloading the page?

**Comment by shakyShane** [comment] 2015-04-13 19:48
It should, yes.

do you have any other places in your code where `.reload` is called?

**Comment by thasmo** [comment] 2015-04-13 19:55
No, actually not. I think I'm going to finish my gulp boilerplate project soonish, where the mentioned watch task is used, and publish it on GitHub anway. I'll poke you when it's published.

**Comment by shakyShane** [comment] 2015-04-13 20:00
Yep, I'll be able to help better when I run the project myself :)

**Comment by thasmo** [comment] 2015-04-13 21:58
@shakyShane, found the source of the problem. It should be `browserSync.reload(file.path);`, not `browserSync.reload(file);`. :) Thanks for your help!

**Comment by atilkan** [comment] 2016-01-08 02:36
I have similar issue should i open new one. Or just share here.
I have a repo for quick starting. 
https://github.com/atilkan/gulp-typescript-stylus-template
The problem is when is, it doesn't stream css files. It reloads. And it detects unchanged files as changes.
I believe this is about watch task, should i go that repo.
