### ISSUE TITLE
Bug with socket.io

### ISSUE THREAD

**Issue by mosaiceye** [BrowserSync/browser-sync#518] opened 2015-03-14 01:58 UTC
[BS] [proxy error] socket hang up. Is this still an open bug:
```js
gulp.task('browser-sync', function() {
    browserSync({
        proxy: "http://localhost:9000",
        files: ["public/**/*.*"],
        port: 9001,
        logConnections: true,
        logLevel: 'debug',
    });
});
```

```json
  "dependencies": {
    "browser-sync": "^2.2.4",
    "express": "^4.12.2",
    "gulp": "^3.8.11",
    "gulp-nodemon": "^1.0.5",
    "socket.io": "^1.3.5"
  }
```
Here's the error I get in the browser: "Connection closed before receiving a handshake response"

What am I missing? Any ideas would be great!

**Comment by shakyShane** [comment] 2015-03-20 18:56
What's your backend? does the url given to you by BrowserSync not show your website?

**Comment by mosaiceye** [comment] 2015-03-20 19:43
Hey Shane-

It's just setup as a node server app. And yes, the URL still works. And so does the socket.io, but it still reports the error, on load because it's going through the BrowserSync proxy. I can send you a link to the repo if that helps. The issue is basically happening between the proxy and the socket connection.

----
Tony Birleffi
e: tony@mosaiceye.com

**Comment by levbrie** [comment] 2015-03-22 22:20
Same issue here

**Comment by shakyShane** [comment] 2015-04-02 16:24
Thanks everyone for the issue report!

This could be an issue with BrowserSync, but right now I cannot be sure - so I'll close this for now.

Should you be able to reproduce this issue in a sample project, please link us to the repo with details about how to see the issue. Once we've verified this is an issue with BrowserSync itself - we'll re-open this ticket and work to resolve it asap.

Thank you for your time - you're helping everyone in the community by reporting any issues you come across :)

**Closed by shakyShane** 2015-04-02 16:24 UTC

**Comment by KaoruDev** [comment] 2015-04-26 18:25
@shakyShane I got a project that's got this bug =)

https://github.com/KaoruDev/SketchyParty/blob/master/client/scripts/apps/displayer/model.js#L8

BrowserSync configs:

https://github.com/KaoruDev/SketchyParty/blob/master/tasks/browser-sync.js

**Comment by KaoruDev** [comment] 2015-04-26 18:30
But interestingly enough it seems to work on the 2nd or 3rd try? My server logs that the socket is connected... weird.

**Comment by KaoruDev** [comment] 2015-04-26 19:38
So the client side wasn't fireing the connect event because there was no room called `foo` once I set that up everything was cool =)

**Comment by shinnn** [comment] 2015-05-08 16:27
@KaoruDev Glad to hear you've solved the problem :)
