### ISSUE TITLE
Empty JavaScript include throws fatal error

### ISSUE THREAD

**Issue by leigeber** [BrowserSync/browser-sync#460] opened 2015-02-17 18:12 UTC
I'm sure this issue originates from down the dependency chain somewhere but after the latest npm update to 2.1.4 if you include an empty external JavaScript file in your markup (```<script src="empty.js"></script>```) you get the following error in the console.

```
Fatal error: start must be <= end
```

In some scenarios it prevents the page from loading altogether. Not sure if other file types are affected.

**Comment by shakyShane** [comment] 2015-02-17 18:49
Yep, we're just waiting for https://github.com/expressjs/serve-static/commit/377aa05778714bd99dca7349f9c97ef1ad4e86d7 to land on npm

**Comment by shakyShane** [comment] 2015-02-17 18:51
Closing as it's a dupe of https://github.com/BrowserSync/browser-sync/issues/456 - when @dougwilson publishes the fix to serve-static, we'll inherit the fix.

**Closed by shakyShane** 2015-02-17 18:51 UTC

**Comment by dougwilson** [comment] 2015-02-17 18:57
aaaaaaaaaand published :)

**Comment by shakyShane** [comment] 2015-02-17 19:20
Thanks @dougwilson.

@leigeber - you're safe now to `npm rm browser-sync && npm install browser-sync` - this will ensure you get the fixes from our dependencies :)

**Comment by leigeber** [comment] 2015-02-17 19:29
Awesome, thanks guys. And sorry for missing the original issue.
